from typing import Protocol


class UserStore(Protocol):
    def create_user(
        self,
        username: str,
        email: str,
        password_hash: str,
        email_verification_code_hash: str,
    ) -> None: ...
    def get_email_verification_code_hash(self, username: str) -> str: ...
    def set_user_verified(self, username: str) -> None: ...
    def is_user_verified(self, username: str) -> bool: ...
    def get_password_hash(self, username: str) -> str: ...
    def add_session(self, username: str, session_token_hash: str) -> None: ...
    def get_session_token_hash(self, username: str) -> str: ...
    def remove_session(self, username: str, session_token_hash: str) -> None: ...
    def remove_all_sessions(self, username: str) -> None: ...
    def set_password_hash(self, username: str, password_hash: str) -> None: ...
    def get_password_reset_token_hash(self, username: str) -> str: ...
    def set_password_reset_token_hash(self, username: str, token_hash: str) -> None: ...
    def is_user_exists(self, username: str, email: str) -> bool: ...
    def delete_user(self, username: str) -> None: ...


class EmailSender(Protocol):
    def send_verification(
        self, username: str, email: str, verification_code: str
    ) -> None: ...
    def send_password_reset(
        self, username: str, email: str, reset_code: str
    ) -> None: ...
