from dataclasses import dataclass
from datetime import datetime
from typing import Protocol


@dataclass
class UserToken:
    username: str
    token_hash: str
    expires_at: datetime


@dataclass
class CreateUserRequest:
    username: str
    email: str
    password: str
    verification_token_hash: str
    expires_at: datetime


class UserStore(Protocol):
    def create_user(self, user: CreateUserRequest) -> None: ...
    def get_email_verification(self, token_hask: str) -> UserToken | None: ...
    def set_email_verification(self, verification: UserToken) -> None: ...
    def remove_email_verification(self, token_hash: str) -> None: ...
    def set_user_verified(self, username: str) -> None: ...
    def is_user_verified(self, username: str) -> bool: ...
    def get_password_hash(self, username: str) -> str: ...
    def add_session(self, session: UserToken) -> None: ...
    def get_session(self, token_hash: str) -> UserToken | None: ...
    def remove_session(self, token_hash: str) -> None: ...
    def remove_all_sessions(self, username: str) -> None: ...
    def set_password_hash(self, username: str, password_hash: str) -> None: ...
    def get_password_reset_token_hash(self, username: str) -> str: ...
    def set_password_reset_token_hash(self, username: str, token_hash: str) -> None: ...
    def remove_password_reset_token_hash(self, username: str) -> None: ...
    def is_user_exists(self, username: str, email: str) -> bool: ...
    def delete_user(self, username: str) -> None: ...


class EmailSender(Protocol):
    def send_verification(
        self, username: str, email: str, verification_code: str
    ) -> None: ...
    def send_password_reset(
        self, username: str, email: str, reset_code: str
    ) -> None: ...
